server:
  port: 8080

routes:
  - name: "Users"
    path: /posts
    upstream: https://dummyjson.com/posts
    methods: 
      - get
    
  - name: "Update Users"
    path: /users
    upstream: https://10.9.0.3:9000/users
    methods:
      - post